import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { issueCompileSandbox } from "./compile-sandbox.js";

test("CompileJob 沙箱签发冻结 CLI、来源和 staging；拒绝重叠根与弱私有目录", { skip: process.platform !== "darwin" }, async () => {
	const root = realpathSync(mkdtempSync(path.join(tmpdir(), "pt-compile-issuer-")));
	const directory = (name: string, mode = 0o700) => {
		const value = path.join(root, name);
		mkdirSync(value, { mode });
		return value;
	};
	const source = directory("source");
	const anotherSource = directory("another-source");
	const staging = directory("staging");
	const privateRoot = directory("private");
	const trusted = directory("trusted");
	const command = path.join(trusted, "codex-stub");
	writeFileSync(command, "#!/bin/sh\nexit 0\n");
	chmodSync(command, 0o755);
	const digest = () => createHash("sha256").update(readFileSync(command)).digest("hex");
	const request = { jobId: "job-one", sourceSnapshotRoot: source, stagingRoot: staging, privateRoot, commandPath: command, commandSha256: digest() };
	const issued = await issueCompileSandbox(request);
	assert.deepEqual(Object.keys(issued.env).sort(), ["HOME", "PATH", "TEMP", "TMP", "TMPDIR"]);
	assert.match(readFileSync(issued.sandboxProfilePath, "utf8"), /\(deny default\)/);
	assert.match(readFileSync(issued.sandboxProfilePath, "utf8"), /\(literal "\/etc\/codex\/requirements\.toml"\)/);
	assert.doesNotMatch(readFileSync(issued.sandboxProfilePath, "utf8"), /\(subpath "\/(?:etc|private\/etc)"\)/);
	assert.doesNotMatch(readFileSync(issued.sandboxProfilePath, "utf8"), /\(allow default\)|\(allow network/);
	assert.doesNotMatch(readFileSync(issued.sandboxProfilePath, "utf8"), /\(subpath "\/(?:usr|Library)"\)/);
	assert.deepEqual(await issueCompileSandbox(request), issued, "same CompileJob may reissue only identical authority");
	const channelRequest = { ...request, privateRoot: directory("private-channel"), modelChannel: { port: 55123 } };
	const channeled = await issueCompileSandbox(channelRequest);
	const channelProfile = readFileSync(channeled.sandboxProfilePath, "utf8");
	assert.match(channelProfile, /\(allow network-outbound \(remote tcp "localhost:55123"\)\)/);
	assert.doesNotMatch(channelProfile, /network-inbound|localhost:55124|\(allow network-outbound\)/);
	assert.deepEqual(channeled.modelChannel, { port: 55123 });
	await assert.rejects(issueCompileSandbox({ ...channelRequest, modelChannel: { port: 55124 } }), /different authority/);
	await assert.rejects(issueCompileSandbox({ ...channelRequest, modelChannel: { port: 0 } }), /invalid CompileJob model channel port/);
	await assert.rejects(issueCompileSandbox({ ...request, sourceSnapshotRoot: anotherSource }), /different authority/);
	await assert.rejects(issueCompileSandbox({ ...request, sourceSnapshotRoot: staging }), /roots must be disjoint/);
	const writableCommand = path.join(staging, "codex-stub");
	writeFileSync(writableCommand, readFileSync(command));
	await assert.rejects(issueCompileSandbox({ ...request, commandPath: writableCommand }), /canonical and outside worker-writable roots/);
	writeFileSync(command, "#!/bin/sh\necho changed\n");
	await assert.rejects(issueCompileSandbox(request), /digest changed/);
	chmodSync(privateRoot, 0o755);
	await assert.rejects(issueCompileSandbox({ ...request, commandSha256: digest() }), /mode 0700/);
});
